#!/bin/bash

# A runit service for Slackware's /etc/rc.d/rc.firewall
# https://docs.slackware.com/howtos:security:basic_security#setup_a_firewall

#sv check inet1 > /dev/null || exit 1

rcd_service="/etc/rc.d/rc.firewall"
if [ -x "${rcd_service}" ]; then
  "${rcd_service}" start
else
  echo "${rcd_service} not executable"
  exit 1
fi

exec chpst -b rc-firewall pause
