#! /bin/sh

exec 2>&1

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
MOUNTPOINT=/sys/fs/fuse/connections

if ! grep -qw fuse /proc/filesystems; then
  echo "Fuse filesystem not loaded."
  exit 
fi
if grep -qw $MOUNTPOINT /proc/mounts; then
  echo -n "Unmounting fuse control filesystem"
  if ! umount $fMOUNTPOINT >/dev/null 2>&1; then
    echo " failed!"
  else
    echo "."
  fi
else
  echo "Fuse control filesystem not mounted."
fi
if grep -qw "^fuse" /proc/modules; then
  echo -n "Unloading fuse module"
  if ! rmmod fuse >/dev/null 2>&1; then
    echo " failed!"
  else
    echo "."
  fi
else
  echo "Fuse module not loaded."
fi
