#! /bin/sh

exec 2>&1

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
MOUNTPOINT=/sys/fs/fuse/connections

# Gracefully exit if the package has been removed.
which fusermount &>/dev/null || sv d fuse

if ! grep -qw fuse /proc/filesystems; then
  echo -n "Loading fuse module"
  if ! modprobe fuse >/dev/null 2>&1; then
    echo " failed!"
    sv d fuse
  else
    echo "."
  fi
else
  echo "Fuse filesystem already available."
fi
if grep -qw fusectl /proc/filesystems && \
  ! grep -qw $MOUNTPOINT /proc/mounts; then
  echo -n "Mounting fuse control filesystem"
  if ! mount -t fusectl fusectl $MOUNTPOINT >/dev/null 2>&1; then
    echo " failed!"
  else
    echo "."
  fi
else
  echo "Fuse control filesystem already available."
fi
exec chpst -b fuse pause
